export const COLLEGES = [
  "Alabama",
  "Georgia",
  "Ohio State",
  "Michigan",
  "LSU",
  "Clemson",
  "Oklahoma",
  "Texas",
  "USC",
  "Notre Dame",
  "Florida State",
  "Oregon",
  "Penn State",
  "Washington",
  "Tennessee",
  "Auburn",
  "Florida",
  "Texas A&M",
  "Miami",
  "TCU",
  "Wisconsin",
  "Iowa",
  "Nebraska",
  "Utah",
  "Kansas State",
  "Mississippi State",
  "Ole Miss",
  "North Carolina",
  "Duke",
  "Pitt",
  "West Virginia",
  "Colorado",
  "Arizona State",
  "Stanford",
  "UCLA",
  "Maryland",
  "Virginia Tech",
  "Baylor",
  "Arkansas",
  "South Carolina",
  "Kentucky",
  "Missouri",
  "Vanderbilt",
  "Indiana",
  "Purdue",
  "Illinois",
  "Minnesota",
  "Northwestern",
  "Rutgers",
  "Iowa State",
  "Texas Tech",
  "Oklahoma State",
  "BYU",
  "Houston",
  "UCF",
  "Cincinnati",
  "Louisville",
  "NC State",
  "Wake Forest",
  "Virginia",
  "Boston College",
  "Syracuse",
  "California",
  "Oregon State",
  "Washington State",
  "Arizona",
  "Colorado State",
  "Fresno State",
  "San Diego State",
  "Boise State",
  "Nevada",
  "UNLV",
  "Air Force",
  "Wyoming",
  "Utah State",
  "New Mexico",
  "San Jose State",
  "Hawaii",
  "SMU",
  "Tulane",
  "Memphis",
  "Temple",
  "East Carolina",
  "South Florida",
  "Florida Atlantic",
  "Florida International",
  "Georgia Tech",
  "Appalachian State",
  "Coastal Carolina",
  "James Madison",
  "Marshall",
  "Old Dominion",
  "Liberty",
  "Western Kentucky",
  "Middle Tennessee",
  "Troy",
  "South Alabama",
  "Louisiana",
  "Louisiana Tech",
  "Arkansas State",
  "Georgia State",
  "Georgia Southern",
  "Southern Miss",
  "UAB",
  "North Texas",
  "Rice",
  "UTSA",
  "Texas State",
  "Sam Houston",
  "Army",
  "Navy",
  "Akron",
  "Bowling Green",
  "Buffalo",
  "Central Michigan",
  "Eastern Michigan",
  "Western Michigan",
  "Kent State",
  "Miami (OH)",
  "Northern Illinois",
  "Ohio",
  "Toledo",
  "Ball State",
  "Charlotte",
  "UTEP",
  "New Mexico State",
  "Montana",
  "Montana State",
  "North Dakota State",
  "South Dakota State",
  "Youngstown State",
  "Eastern Washington",
  "Villanova",
  "Delaware",
  "Richmond",
  "William & Mary"
];
